name: Test Frontend Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Frontend
        run: |
          docker build -t frontend -f frontend/Dockerfile frontend/

      - name: Run Frontend Container
        run: |
          docker run -d --name frontend -p 19006:19006 frontend
