name: Test Backend Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Backend
        run: |
          docker build -t backend -f backend/Dockerfile backend/

      - name: Run Backend Container
        run: |
          docker run -d --name backend -p 11000:11000 backend
          sleep 5  # Wait for the backend to initialize

      - name: Run Pytest inside Docker
        run: |
          docker exec backend pytest --disable-warnings -s -v

      - name: Stop and remove the container
        if: always()
        run: |
          docker stop backend
          docker rm backend
